# Generated by Django 4.2.3 on 2023-07-31 15:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import playdate.photos.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("playgrounds", "0004_delete_photo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "playground_image",
                    models.ImageField(
                        upload_to="playground_photos",
                        validators=[
                            playdate.photos.validators.image_size_validator_5mb
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=300,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(300)],
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=50, null=True)),
                ("date_of_publication", models.DateField(auto_now=True)),
                (
                    "playground_name",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="playgrounds.playground",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
