# Generated by Django 4.2.3 on 2023-08-01 08:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="description",
            field=models.TextField(
                blank=True,
                max_length=300,
                null=True,
                validators=[django.core.validators.MinLengthValidator(5)],
            ),
        ),
    ]
