# Generated by Django 4.2.3 on 2023-07-30 07:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playdateuser",
            name="first_name",
            field=models.CharField(
                blank=True,
                max_length=30,
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(2),
                    django.core.validators.RegexValidator(
                        "^[A-Z][A-z]*$", "Your name must start with a capital letter!"
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="playdateuser",
            name="last_name",
            field=models.CharField(
                blank=True,
                max_length=30,
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(2),
                    django.core.validators.RegexValidator(
                        "^[A-Z][A-z]*$", "Your name must start with a capital letter!"
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="playdateuser",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures"
            ),
        ),
    ]
