# Generated by Django 4.2.3 on 2023-07-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_playdateuser_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playdateuser",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/"
            ),
        ),
    ]
