# Generated by Django 4.2.3 on 2023-08-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_alter_playdateuser_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playdateuser",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_picture/"
            ),
        ),
    ]
