# Generated by Django 4.2.3 on 2023-07-31 15:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "playgrounds",
            "0003_playground_rating_playground_slug_playground_website_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="Photo",
        ),
    ]
